package com.yubaraj.test;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneLayout;

/**
 *
 * @author Yuba Raj Kalathoki
 */
public class DisplayDynamicValuesInCheckBox extends javax.swing.JFrame {

    List<JCheckBox> checkBoxes = new ArrayList<>();

    /**
     * Creates new form DisplayDynamicValuesInCheckBox
     */
    public DisplayDynamicValuesInCheckBox() {
        initComponents();

        jPanel1.setLayout(new GridLayout(0, 2, 10, 10));
//        JScrollPane jScrollPane = new JScrollPane(jPanel1);

        List<String> students = new ArrayList<String>();
        students.add("A");
        students.add("B");
        students.add("C");
        students.add("D");
        students.add("E");
        students.add("F");
        students.add("F");
        students.add("G");
        students.add("H");
        students.add("I");
        students.add("J");
        students.add("K");
        students.add("A");
        students.add("B");
        students.add("C");
        students.add("D");
        students.add("E");
        students.add("F");
        students.add("F");
        students.add("G");
        students.add("H");
        students.add("I");
        students.add("J");
        students.add("K");
        students.add("C");
        students.add("D");
        students.add("E");
        students.add("F");
        students.add("F");
        students.add("G");
        students.add("H");
        students.add("I");
        students.add("J");
        students.add("K");
        students.add("A");
        students.add("B");
        students.add("C");
        students.add("D");
        students.add("E");
        students.add("F");
        students.add("F");
        students.add("G");
        students.add("H");
        students.add("I");
        students.add("J");
        students.add("K");
        students.add("C");
        students.add("D");
        students.add("E");
        students.add("F");
        students.add("F");
        students.add("G");
        students.add("H");
        students.add("I");
        students.add("J");
        students.add("K");
        students.add("A");
        students.add("B");
        students.add("C");
        students.add("D");
        students.add("E");
        students.add("F");
        students.add("F");
        students.add("G");
        students.add("H");
        students.add("I");
        students.add("J");
        students.add("K");

        for (String s : students) {
            JCheckBox jCheckBox1 = new JCheckBox();
            jCheckBox1.setText(s);
            checkBoxes.add(jCheckBox1);
            jPanel1.add(jCheckBox1);
//            this.add(jScrollPane1);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jButton1)
                .addContainerGap(187, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        List<String> values = new ArrayList();
        for (JCheckBox c : checkBoxes) {
            if (c.isSelected()) {
                values.add(c.getText());
            }
        }
        JOptionPane.showMessageDialog(null, values);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayDynamicValuesInCheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayDynamicValuesInCheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayDynamicValuesInCheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayDynamicValuesInCheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayDynamicValuesInCheckBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
