package com.texas.csit.attendance;

import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Yuba Raj Kalathoki
 */
public class AttendanceAddPanel extends javax.swing.JPanel {

    ArrayList<JCheckBox> checkBoxes = new ArrayList<>();
    /**
     * Creates new form AttendanceAddPanel
     */
    public AttendanceAddPanel() {
        initComponents();
//        displayStudentsForAttendance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentScrollPane = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
        );

        studentScrollPane.setViewportView(jPanel1);

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(addButton)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentScrollPane)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        ArrayList<String> selectedStudents = new ArrayList();
        for(JCheckBox c: checkBoxes){
            if(c.isSelected()){
                selectedStudents.add(c.getText());
            }
        }
        
        Date attendanceDate = new Date();
        Timestamp timestamp = new  Timestamp(attendanceDate.getTime());
        
        Connection cn = DatabaseConnection.getConnection();
        try {
           for(String rollNo: selectedStudents){ 
                Statement stat = cn.createStatement();
                String sql = "insert into attendanc_info (roll_no, attendance_status, attendance_date) values ("+rollNo+", 'P', '"+timestamp+"')" ;
                stat.executeUpdate(sql);
           }
           JOptionPane.showMessageDialog(null, "Attendance updated!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Failed!");
        }
        
    }//GEN-LAST:event_addButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane studentScrollPane;
    // End of variables declaration//GEN-END:variables

    public void displayStudentsForAttendance() {
        jPanel1.removeAll();
         jPanel1.setLayout(new GridLayout(0, 2, 10, 10));
        Connection cn = DatabaseConnection.getConnection();

        String sql = "Select * from student";

        ArrayList<String> studentList = new ArrayList<>();
        try {
            Statement stat = cn.createStatement();
            ResultSet rs = stat.executeQuery(sql);

            while (rs.next()) {
                String name = rs.getString("roll_number");
                studentList.add(name);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        System.out.println("student list : " + studentList);
        for (String s : studentList) {
            JCheckBox cb = new JCheckBox();
            cb.setText(s);
            checkBoxes.add(cb);// for button functionality
            jPanel1.add(cb);
        }

    }
}
