package com.texas.csit.attendance;

import java.awt.BorderLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Yuba Raj Kalathoki
 */
public class MainForm extends javax.swing.JFrame {

    private StudentRegisterPanel studentRegisterPanel;
    private StudentEditPanel studentEditPanel;
    private AttendanceAddPanel attendanceAddPanel;
    private AttendanceEditPanel attendanceEditPanel;
    private DashboardPanel dashboardPanel;
private StudentDetailsPanel studentDetailsPanel;
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();

        /**
         * Minimize frame when user clicks close button
         */
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
//                setExtendedState(JFrame.ICONIFIED);

                if (JOptionPane.showConfirmDialog(null,
                        "Are you sure to close this window?", "Really Closing?",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION) {
                    System.exit(0);
                }
            }
        });

        //centering jframe
        setLocationRelativeTo(null);

        /**
         * Home button visible false default
         */
        homeButton.setVisible(false);

        mainPanel.setLayout(new BorderLayout());

        //init objects
        studentRegisterPanel = new StudentRegisterPanel();
        studentEditPanel = new StudentEditPanel();
        attendanceAddPanel = new AttendanceAddPanel();
        attendanceEditPanel = new AttendanceEditPanel();
        dashboardPanel = new DashboardPanel();
        studentDetailsPanel=new StudentDetailsPanel();
        
        /**
         * Displaying dash board panel in default
         */
        mainPanel.add(dashboardPanel, BorderLayout.CENTER);
        dashboardPanel.setVisible(true);

        //setting default visible false
        studentRegisterPanel.setVisible(false);
        studentEditPanel.setVisible(false);
        attendanceAddPanel.setVisible(false);
        attendanceEditPanel.setVisible(false);
        studentDetailsPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        footerPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        studentRegisterMenuItem = new javax.swing.JMenuItem();
        addendanceAddMenuItem = new javax.swing.JMenuItem();
        attendanceEditMenuItem = new javax.swing.JMenu();
        studentEditMenuItem = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        studentViewMenuItem = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Attendance Management System");
        setPreferredSize(new java.awt.Dimension(650, 650));
        setResizable(false);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        footerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("Exit");
        jButton1.setToolTipText("Click to exit application");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        homeButton.setText("Home");

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(homeButton))
                .addContainerGap())
        );

        jMenu1.setText("New");

        studentRegisterMenuItem.setText("Student");
        studentRegisterMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentRegisterMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(studentRegisterMenuItem);

        addendanceAddMenuItem.setText("Attendance");
        addendanceAddMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addendanceAddMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(addendanceAddMenuItem);

        jMenuBar1.add(jMenu1);

        attendanceEditMenuItem.setText("Edit");

        studentEditMenuItem.setText("Student");
        studentEditMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentEditMenuItemActionPerformed(evt);
            }
        });
        attendanceEditMenuItem.add(studentEditMenuItem);

        jMenuItem4.setText("Attendance");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        attendanceEditMenuItem.add(jMenuItem4);

        jMenuBar1.add(attendanceEditMenuItem);

        jMenu3.setText("View");

        studentViewMenuItem.setText("Student");
        studentViewMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentViewMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(studentViewMenuItem);

        jMenuItem6.setText("Attendance");
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(footerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(footerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentRegisterMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentRegisterMenuItemActionPerformed
//        studentRegisterPanel = new StudentRegisterPanel();
        mainPanel.add(studentRegisterPanel, BorderLayout.CENTER);
        studentRegisterPanel.setVisible(true);

        homeButton.setVisible(true);
        dashboardPanel.setVisible(false);
        studentEditPanel.setVisible(false);
        attendanceAddPanel.setVisible(false);
        attendanceEditPanel.setVisible(false);
        studentDetailsPanel.setVisible(false);
    }//GEN-LAST:event_studentRegisterMenuItemActionPerformed

    private void studentEditMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentEditMenuItemActionPerformed
//        studentEditPanel = new StudentEditPanel();
        mainPanel.add(studentEditPanel, BorderLayout.CENTER);
        studentEditPanel.setVisible(true);

        homeButton.setVisible(true);
        dashboardPanel.setVisible(false);
        studentRegisterPanel.setVisible(false);
        attendanceAddPanel.setVisible(false);
        attendanceEditPanel.setVisible(false);
        studentDetailsPanel.setVisible(false);
    }//GEN-LAST:event_studentEditMenuItemActionPerformed

    private void addendanceAddMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addendanceAddMenuItemActionPerformed
//        attendanceAddPanel = new AttendanceAddPanel();
        mainPanel.add(attendanceAddPanel, BorderLayout.CENTER);
        attendanceAddPanel.setVisible(true);
        attendanceAddPanel.displayStudentsForAttendance();

        homeButton.setVisible(true);
        dashboardPanel.setVisible(false);
        studentRegisterPanel.setVisible(false);
        studentEditPanel.setVisible(false);
        attendanceEditPanel.setVisible(false);
        studentDetailsPanel.setVisible(false);
    }//GEN-LAST:event_addendanceAddMenuItemActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        mainPanel.add(attendanceEditPanel, BorderLayout.CENTER);
        attendanceEditPanel.setVisible(true);

        homeButton.setVisible(true);
        dashboardPanel.setVisible(false);
        attendanceEditPanel.displayStudentsRollNoToEditAttendance();
        studentRegisterPanel.setVisible(false);
        studentEditPanel.setVisible(false);
        attendanceAddPanel.setVisible(false);
        studentDetailsPanel.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /**
         * ask confirmation when user clicks exit button
         */
        if (JOptionPane.showConfirmDialog(this,
                "Are you sure to close this application?", "Really Closing?",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void studentViewMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentViewMenuItemActionPerformed
         mainPanel.add(studentDetailsPanel, BorderLayout.CENTER);
        studentDetailsPanel.setVisible(true);

        homeButton.setVisible(true);
        dashboardPanel.setVisible(false);
        attendanceEditPanel.displayStudentsRollNoToEditAttendance();
        studentRegisterPanel.setVisible(false);
        studentEditPanel.setVisible(false);
        attendanceAddPanel.setVisible(false);
        attendanceEditPanel.setVisible(false);
    }//GEN-LAST:event_studentViewMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addendanceAddMenuItem;
    private javax.swing.JMenu attendanceEditMenuItem;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem studentEditMenuItem;
    private javax.swing.JMenuItem studentRegisterMenuItem;
    private javax.swing.JMenuItem studentViewMenuItem;
    // End of variables declaration//GEN-END:variables
}
